[build]
builder = "Nixpacks"

[build.nixpacks]
pkgs = [
    "ffmpeg",
    "python3",
    "pip",
    "cargo",
    "rust",
    "gcc",
    "libsodium-dev",
    "pkg-config"
]

[start]
cmd = "pip install --upgrade PyNaCl && python3 main.py"
